################################################################################
# \file bsp.mk
#
################################################################################
# \copyright
# Copyright (c) 2018-2026 Infineon Technologies AG
# an affiliate of Infineon Technologies AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
BSP_COMPONENTS:=

# Any additional defines to apply when using this board.
BSP_DEFINES:=

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=PSC1M3FBLGQ0AT
DEVICE:=PSC1M3FBLGQ0AT
BSP_DEVICE_SUPPORT_LIB:=mtb-dsl-psc1m3
DEVICE_COMPONENTS:=PSC1 PSC1M3
DEVICE_LIST:=PSC1M3FBLGQ0AT
DEVICE_PSC1M3FBLGQ0AT_CORES:=CORE_NAME_CM0_0
DEVICE_PSC1M3FBLGQ0AT_DIE:=PSC1M
DEVICE_PSC1M3FBLGQ0AT_FLASH_KB:=200
DEVICE_PSC1M3FBLGQ0AT_IPBLOCKS:=PSC1_ACMP PSC1_ACMP_V1 PSC1_BCCU PSC1_BCCU_V1 PSC1_CAN PSC1_CAN_V2 PSC1_CCU4 PSC1_CCU4_V3 PSC1_CCU8 PSC1_CCU8_V3 PSC1_CPUSS PSC1_CPUSS_V1 PSC1_ERU PSC1_ERU_V1 PSC1_FLASH PSC1_FLASH_V1 PSC1_IOSS PSC1_IOSS_V1 PSC1_LEDTS PSC1_LEDTS_V1 PSC1_MATH PSC1_MATH_V1 PSC1_ORC PSC1_ORC_V1 PSC1_PAU PSC1_PAU_V1 PSC1_POSIF PSC1_POSIF_V1 PSC1_PRNG PSC1_PRNG_V1 PSC1_RTC PSC1_RTC_V1 PSC1_SCU PSC1_SCU_V1 PSC1_USIC PSC1_USIC_V1 PSC1_VADC PSC1_VADC_V1 PSC1_WDT PSC1_WDT_V1
DEVICE_PSC1M3FBLGQ0AT_SRAM_KB:=16
DEVICE_TOOL_IDS:=bsp-assistant device-configurator library-manager mtb-live-monitor project-creator
RECIPE_DIR:=$(SEARCH_mtb-dsl-psc1m3)/make
